In [1]:
import duckdb

con = duckdb.connect("bronze_staging_db.duckdb")

In [2]:
con.execute("Select count(*),count(distinct unique_key) from staging_bronze").fetchall()

[(946320, 946320)]

In [3]:
df=con.execute("select * from staging_bronze limit 100").fetchdf()

In [5]:
con.execute("describe staging_bronze").fetchall()

[('unique_key', 'VARCHAR', 'YES', None, None, None),
 ('created_date', 'VARCHAR', 'YES', None, None, None),
 ('closed_date', 'VARCHAR', 'YES', None, None, None),
 ('agency', 'VARCHAR', 'YES', None, None, None),
 ('agency_name', 'VARCHAR', 'YES', None, None, None),
 ('complaint_type', 'VARCHAR', 'YES', None, None, None),
 ('descriptor', 'VARCHAR', 'YES', None, None, None),
 ('descriptor_2', 'VARCHAR', 'YES', None, None, None),
 ('incident_zip', 'VARCHAR', 'YES', None, None, None),
 ('incident_address', 'VARCHAR', 'YES', None, None, None),
 ('street_name', 'VARCHAR', 'YES', None, None, None),
 ('cross_street_1', 'VARCHAR', 'YES', None, None, None),
 ('cross_street_2', 'VARCHAR', 'YES', None, None, None),
 ('address_type', 'VARCHAR', 'YES', None, None, None),
 ('city', 'VARCHAR', 'YES', None, None, None),
 ('status', 'VARCHAR', 'YES', None, None, None),
 ('resolution_description', 'VARCHAR', 'YES', None, None, None),
 ('resolution_action_updated_date', 'VARCHAR', 'YES', None, None, None),
 ('community_board', 'VARCHAR', 'YES', None, None, None),
 ('council_district', 'VARCHAR', 'YES', None, None, None),
 ('police_precinct', 'VARCHAR', 'YES', None, None, None),
 ('bbl', 'VARCHAR', 'YES', None, None, None),
 ('borough', 'VARCHAR', 'YES', None, None, None),
 ('x_coordinate_state_plane', 'VARCHAR', 'YES', None, None, None),
 ('y_coordinate_state_plane', 'VARCHAR', 'YES', None, None, None),
 ('open_data_channel_type', 'VARCHAR', 'YES', None, None, None),
 ('park_facility_name', 'VARCHAR', 'YES', None, None, None),
 ('park_borough', 'VARCHAR', 'YES', None, None, None),
 ('latitude', 'VARCHAR', 'YES', None, None, None),
 ('longitude', 'VARCHAR', 'YES', None, None, None),
 ('location', 'VARCHAR', 'YES', None, None, None),
 ('facility_type', 'VARCHAR', 'YES', None, None, None),
 ('intersection_street_1', 'VARCHAR', 'YES', None, None, None),
 ('intersection_street_2', 'VARCHAR', 'YES', None, None, None),
 ('location_type', 'VARCHAR', 'YES', None, None, None),
 ('landmark', 'VARCHAR', 'YES', None, None, None),
 ('due_date', 'VARCHAR', 'YES', None, None, None),
 ('vehicle_type', 'VARCHAR', 'YES', None, None, None),
 ('taxi_pick_up_location', 'VARCHAR', 'YES', None, None, None),
 ('bridge_highway_name', 'VARCHAR', 'YES', None, None, None),
 ('bridge_highway_direction', 'VARCHAR', 'YES', None, None, None),
 ('bridge_highway_segment', 'VARCHAR', 'YES', None, None, None),
 ('road_ramp', 'VARCHAR', 'YES', None, None, None),
 ('taxi_company_borough', 'VARCHAR', 'YES', None, None, None),
 ('ingest_timestamp', 'TIMESTAMP', 'YES', None, None, None)]

In [30]:
con.execute("""
SELECT
    CAST(unique_key AS VARCHAR) AS unique_key,
    CAST(created_date AS TIMESTAMP) AS created_date,
    CAST(closed_date AS TIMESTAMP) AS closed_date,
    CAST(agency AS VARCHAR) AS agency,
    CAST(agency_name AS VARCHAR) AS agency_name,
    CAST(complaint_type AS VARCHAR) AS complaint_type,
    CAST(descriptor AS VARCHAR) AS descriptor,
    CAST(descriptor_2 AS VARCHAR) AS descriptor_2,
    CAST(location_type AS VARCHAR) AS location_type,
    CAST(incident_zip AS VARCHAR) AS incident_zip,
    CAST(incident_address AS VARCHAR) AS incident_address,
    CAST(street_name AS VARCHAR) AS street_name,
    CAST(cross_street_1 AS VARCHAR) AS cross_street_1,
    CAST(cross_street_2 AS VARCHAR) AS cross_street_2,
    CAST(intersection_street_1 AS VARCHAR) AS intersection_street_1,
    CAST(intersection_street_2 AS VARCHAR) AS intersection_street_2,
    CAST(address_type AS VARCHAR) AS address_type,
    CAST(city AS VARCHAR) AS city,
    CAST(landmark AS VARCHAR) AS landmark,
    CAST(facility_type AS VARCHAR) AS facility_type,
    CAST(status AS VARCHAR) AS status,
    CAST(due_date AS TIMESTAMP) AS due_date,
    CAST(resolution_description AS VARCHAR) AS resolution_description,
    CAST(resolution_action_updated_date AS TIMESTAMP) AS resolution_action_updated_date,
    CAST(community_board AS VARCHAR) AS community_board,
    CAST(council_district AS INTEGER) AS council_district,
    CAST(police_precinct AS VARCHAR) AS police_precinct,
    CAST(bbl AS VARCHAR) AS bbl,
    CAST(borough AS VARCHAR) AS borough,
    CAST(x_coordinate_state_plane AS DOUBLE) AS x_coordinate_state_plane,
    CAST(y_coordinate_state_plane AS DOUBLE) AS y_coordinate_state_plane,
    CAST(open_data_channel_type AS VARCHAR) AS open_data_channel_type,
    CAST(park_facility_name AS VARCHAR) AS park_facility_name,
    CAST(park_borough AS VARCHAR) AS park_borough,
    CAST(vehicle_type AS VARCHAR) AS vehicle_type,
    CAST(taxi_company_borough AS VARCHAR) AS taxi_company_borough,
    CAST(taxi_pick_up_location AS VARCHAR) AS taxi_pick_up_location,
    CAST(bridge_highway_name AS VARCHAR) AS bridge_highway_name,
    CAST(bridge_highway_direction AS VARCHAR) AS bridge_highway_direction,
    CAST(road_ramp AS VARCHAR) AS road_ramp,
    CAST(bridge_highway_segment AS VARCHAR) AS bridge_highway_segment,
    CAST(latitude AS DOUBLE) AS latitude,
    CAST(longitude AS DOUBLE) AS longitude,
    cast(location as varchar) as location , 
    cast(ingest_timestamp as Timestamp)
FROM staging_bronze limit 100""").fetchdf().head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,CAST(ingest_timestamp AS TIMESTAMP)
0,68547644,2026-04-03 10:40:00,2026-04-03 11:00:00,DEP,Department of Environmental Protection,Hazardous Materials,"Oil Spill On Street, Small (HQS)",HQS,NaN,10314,...,None,NaN,None,None,None,None,40.590712,-74.155047,"{'type': Point, 'coordinates': [-74.1550469528...",2026-07-02 09:10:30
1,68547645,2026-04-03 11:55:00,2026-04-03 11:55:00,DEP,Department of Environmental Protection,Water System,Hyd Valve Box Cover Missing (WV2),WV2,NaN,10009,...,None,NaN,None,None,None,None,40.721678,-73.980605,"{'type': Point, 'coordinates': [-73.9806054072...",2026-07-02 09:10:30
2,68547646,2026-04-03 22:44:00,2026-04-06 20:06:00,DEP,Department of Environmental Protection,Noise,Noise: Manufacturing Noise (NK1),NK1,NaN,10454,...,None,NaN,None,None,None,None,40.807450,-73.919280,"{'type': Point, 'coordinates': [-73.9192801132...",2026-07-02 09:10:30
3,68547647,2026-04-03 15:14:00,2026-04-03 23:40:00,DEP,Department of Environmental Protection,Water System,High Water Pressure (WHP),WHP,NaN,10013,...,None,NaN,None,None,None,None,40.720437,-74.000988,"{'type': Point, 'coordinates': [-74.0009884708...",2026-07-02 09:10:30
4,68547649,2026-04-03 23:15:00,2026-04-06 19:29:00,DEP,Department of Environmental Protection,Noise,Noise: air condition/ventilation equipment (NV1),NV1,NaN,11101,...,None,NaN,None,None,None,None,40.742291,-73.959358,"{'type': Point, 'coordinates': [-73.9593583544...",2026-07-02 09:10:30

In [29]:
con.execute("select * from staging_bronze limit 1").fetchdf().head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,incident_zip,incident_address,...,landmark,due_date,vehicle_type,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,bridge_highway_segment,road_ramp,taxi_company_borough,ingest_timestamp
0,68547644,2026-04-03T10:40:00.000,2026-04-03T11:00:00.000,DEP,Department of Environmental Protection,Hazardous Materials,"Oil Spill On Street, Small (HQS)",HQS,10314,202 BRAISTED AVENUE,...,None,None,None,None,None,None,None,None,None,2026-07-02 09:10:30

In [12]:
select_expr =[]
for col in dict.keys() :
    select_expr.append(f'CAST("{col}" AS VARCHAR) AS "{col}"')
print(select_expr)

['CAST("unique_key" AS VARCHAR) AS "unique_key"', 'CAST("created_date" AS VARCHAR) AS "created_date"', 'CAST("closed_date" AS VARCHAR) AS "closed_date"', 'CAST("agency" AS VARCHAR) AS "agency"', 'CAST("agency_name" AS VARCHAR) AS "agency_name"', 'CAST("complaint_type" AS VARCHAR) AS "complaint_type"', 'CAST("descriptor" AS VARCHAR) AS "descriptor"', 'CAST("descriptor_2" AS VARCHAR) AS "descriptor_2"', 'CAST("incident_zip" AS VARCHAR) AS "incident_zip"', 'CAST("incident_address" AS VARCHAR) AS "incident_address"', 'CAST("street_name" AS VARCHAR) AS "street_name"', 'CAST("cross_street_1" AS VARCHAR) AS "cross_street_1"', 'CAST("cross_street_2" AS VARCHAR) AS "cross_street_2"', 'CAST("address_type" AS VARCHAR) AS "address_type"', 'CAST("city" AS VARCHAR) AS "city"', 'CAST("status" AS VARCHAR) AS "status"', 'CAST("resolution_description" AS VARCHAR) AS "resolution_description"', 'CAST("resolution_action_updated_date" AS VARCHAR) AS "resolution_action_updated_date"', 'CAST("community_board" AS VARCHAR) AS "community_board"', 'CAST("council_district" AS VARCHAR) AS "council_district"', 'CAST("police_precinct" AS VARCHAR) AS "police_precinct"', 'CAST("bbl" AS VARCHAR) AS "bbl"', 'CAST("borough" AS VARCHAR) AS "borough"', 'CAST("x_coordinate_state_plane" AS VARCHAR) AS "x_coordinate_state_plane"', 'CAST("y_coordinate_state_plane" AS VARCHAR) AS "y_coordinate_state_plane"', 'CAST("open_data_channel_type" AS VARCHAR) AS "open_data_channel_type"', 'CAST("park_facility_name" AS VARCHAR) AS "park_facility_name"', 'CAST("park_borough" AS VARCHAR) AS "park_borough"', 'CAST("latitude" AS VARCHAR) AS "latitude"', 'CAST("longitude" AS VARCHAR) AS "longitude"', 'CAST("location" AS VARCHAR) AS "location"', 'CAST("facility_type" AS VARCHAR) AS "facility_type"', 'CAST("intersection_street_1" AS VARCHAR) AS "intersection_street_1"', 'CAST("intersection_street_2" AS VARCHAR) AS "intersection_street_2"', 'CAST("location_type" AS VARCHAR) AS "location_type"', 'CAST("landmark" AS VARCHAR) AS "landmark"', 'CAST("due_date" AS VARCHAR) AS "due_date"', 'CAST("vehicle_type" AS VARCHAR) AS "vehicle_type"', 'CAST("taxi_pick_up_location" AS VARCHAR) AS "taxi_pick_up_location"', 'CAST("bridge_highway_name" AS VARCHAR) AS "bridge_highway_name"', 'CAST("bridge_highway_direction" AS VARCHAR) AS "bridge_highway_direction"', 'CAST("bridge_highway_segment" AS VARCHAR) AS "bridge_highway_segment"', 'CAST("road_ramp" AS VARCHAR) AS "road_ramp"', 'CAST("taxi_company_borough" AS VARCHAR) AS "taxi_company_borough"', 'CAST("ingest_timestamp" AS VARCHAR) AS "ingest_timestamp"']

In [19]:
print(f"SELECT {select_expr} ")

print(select_sql)

SELECT ['CAST("unique_key" AS VARCHAR) AS "unique_key"', 'CAST("created_date" AS VARCHAR) AS "created_date"', 'CAST("closed_date" AS VARCHAR) AS "closed_date"', 'CAST("agency" AS VARCHAR) AS "agency"', 'CAST("agency_name" AS VARCHAR) AS "agency_name"', 'CAST("complaint_type" AS VARCHAR) AS "complaint_type"', 'CAST("descriptor" AS VARCHAR) AS "descriptor"', 'CAST("descriptor_2" AS VARCHAR) AS "descriptor_2"', 'CAST("incident_zip" AS VARCHAR) AS "incident_zip"', 'CAST("incident_address" AS VARCHAR) AS "incident_address"', 'CAST("street_name" AS VARCHAR) AS "street_name"', 'CAST("cross_street_1" AS VARCHAR) AS "cross_street_1"', 'CAST("cross_street_2" AS VARCHAR) AS "cross_street_2"', 'CAST("address_type" AS VARCHAR) AS "address_type"', 'CAST("city" AS VARCHAR) AS "city"', 'CAST("status" AS VARCHAR) AS "status"', 'CAST("resolution_description" AS VARCHAR) AS "resolution_description"', 'CAST("resolution_action_updated_date" AS VARCHAR) AS "resolution_action_updated_date"', 'CAST("community_board" AS VARCHAR) AS "community_board"', 'CAST("council_district" AS VARCHAR) AS "council_district"', 'CAST("police_precinct" AS VARCHAR) AS "police_precinct"', 'CAST("bbl" AS VARCHAR) AS "bbl"', 'CAST("borough" AS VARCHAR) AS "borough"', 'CAST("x_coordinate_state_plane" AS VARCHAR) AS "x_coordinate_state_plane"', 'CAST("y_coordinate_state_plane" AS VARCHAR) AS "y_coordinate_state_plane"', 'CAST("open_data_channel_type" AS VARCHAR) AS "open_data_channel_type"', 'CAST("park_facility_name" AS VARCHAR) AS "park_facility_name"', 'CAST("park_borough" AS VARCHAR) AS "park_borough"', 'CAST("latitude" AS VARCHAR) AS "latitude"', 'CAST("longitude" AS VARCHAR) AS "longitude"', 'CAST("location" AS VARCHAR) AS "location"', 'CAST("facility_type" AS VARCHAR) AS "facility_type"', 'CAST("intersection_street_1" AS VARCHAR) AS "intersection_street_1"', 'CAST("intersection_street_2" AS VARCHAR) AS "intersection_street_2"', 'CAST("location_type" AS VARCHAR) AS "location_type"', 'CAST("landmark" AS VARCHAR) AS "landmark"', 'CAST("due_date" AS VARCHAR) AS "due_date"', 'CAST("vehicle_type" AS VARCHAR) AS "vehicle_type"', 'CAST("taxi_pick_up_location" AS VARCHAR) AS "taxi_pick_up_location"', 'CAST("bridge_highway_name" AS VARCHAR) AS "bridge_highway_name"', 'CAST("bridge_highway_direction" AS VARCHAR) AS "bridge_highway_direction"', 'CAST("bridge_highway_segment" AS VARCHAR) AS "bridge_highway_segment"', 'CAST("road_ramp" AS VARCHAR) AS "road_ramp"', 'CAST("taxi_company_borough" AS VARCHAR) AS "taxi_company_borough"', 'CAST("ingest_timestamp" AS VARCHAR) AS "ingest_timestamp"']
CAST("unique_key" AS VARCHAR) AS "unique_key",
CAST("created_date" AS VARCHAR) AS "created_date",
CAST("closed_date" AS VARCHAR) AS "closed_date",
CAST("agency" AS VARCHAR) AS "agency",
CAST("agency_name" AS VARCHAR) AS "agency_name",
CAST("complaint_type" AS VARCHAR) AS "complaint_type",
CAST("descriptor" AS VARCHAR) AS "descriptor",
CAST("descriptor_2" AS VARCHAR) AS "descriptor_2",
CAST("incident_zip" AS VARCHAR) AS "incident_zip",
CAST("incident_address" AS VARCHAR) AS "incident_address",
CAST("street_name" AS VARCHAR) AS "street_name",
CAST("cross_street_1" AS VARCHAR) AS "cross_street_1",
CAST("cross_street_2" AS VARCHAR) AS "cross_street_2",
CAST("address_type" AS VARCHAR) AS "address_type",
CAST("city" AS VARCHAR) AS "city",
CAST("status" AS VARCHAR) AS "status",
CAST("resolution_description" AS VARCHAR) AS "resolution_description",
CAST("resolution_action_updated_date" AS VARCHAR) AS "resolution_action_updated_date",
CAST("community_board" AS VARCHAR) AS "community_board",
CAST("council_district" AS VARCHAR) AS "council_district",
CAST("police_precinct" AS VARCHAR) AS "police_precinct",
CAST("bbl" AS VARCHAR) AS "bbl",
CAST("borough" AS VARCHAR) AS "borough",
CAST("x_coordinate_state_plane" AS VARCHAR) AS "x_coordinate_state_plane",
CAST("y_coordinate_state_plane" AS VARCHAR) AS "y_coordinate_state_plane",
CAST("open_data_channel_type" AS VARCHAR) AS "open_data_channel_type",
CAST("park_facility_name" AS VARCHAR) AS "park_facility_name",
CAST("park_borough" AS VARCHAR) AS "park_borough",
CAST("latitude" AS VARCHAR) AS "latitude",
CAST("longitude" AS VARCHAR) AS "longitude",
CAST("location" AS VARCHAR) AS "location",
CAST("facility_type" AS VARCHAR) AS "facility_type",
CAST("intersection_street_1" AS VARCHAR) AS "intersection_street_1",
CAST("intersection_street_2" AS VARCHAR) AS "intersection_street_2",
CAST("location_type" AS VARCHAR) AS "location_type",
CAST("landmark" AS VARCHAR) AS "landmark",
CAST("due_date" AS VARCHAR) AS "due_date",
CAST("vehicle_type" AS VARCHAR) AS "vehicle_type",
CAST("taxi_pick_up_location" AS VARCHAR) AS "taxi_pick_up_location",
CAST("bridge_highway_name" AS VARCHAR) AS "bridge_highway_name",
CAST("bridge_highway_direction" AS VARCHAR) AS "bridge_highway_direction",
CAST("bridge_highway_segment" AS VARCHAR) AS "bridge_highway_segment",
CAST("road_ramp" AS VARCHAR) AS "road_ramp",
CAST("taxi_company_borough" AS VARCHAR) AS "taxi_company_borough",
CAST("ingest_timestamp" AS VARCHAR) AS "ingest_timestamp"

In [20]:
con.close()